version: '3.8'

services:
  backend:
    build:
      context: ./backend/demo
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  frontend:
      build: ./frontend
      container_name: frontend-container
      ports:
        - "3000:3000"
      depends_on:
        - backend

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
